version: '2'
services:
  app:
    container_name: app
    build: .
    volumes:
      - ./:/app
    restart: always
    working_dir: /app
    depends_on:
      - database
    ports:
      - 3000:3000
    command: npm run start:dev
    networks:
      - net

  database:
    container_name: database
    image: mongo:4.2.7
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=developer
    ports:
      - 27017:27017
    networks:
      - net
    volumes:
      - database:/data/db
      - database_config:/data/configdb

volumes:
  database:
  database_config:

networks:
  net:
    driver: bridge
