version: '2'
services:
  app:
    container_name: app
    build: .
    volumes:
      - ./:/app
    restart: always
    working_dir: /app
    depends_on:
      - database
    ports:
      - 3000:3000
    command: npm run start:dev
    networks:
      - net

  database:
    container_name: database
    image: postgres
    restart: always
    environment:
      TZ: 'GMT+7'
      PGTZ: 'GMT+7'
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - 5432:5432
    networks:
      - net

  sonarqube:
    container_name: sonarqube
    image: sonarqube:latest
    ports:
      - 9000:9000
    networks:
      - net

networks:
  net:
    driver: bridge
